services:
  - type: web
    name: ai-reply-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://api.groq.com/openai/v1
      - key: OPENAI_MODEL
        value: llama-3.3-70b-versatile
      - key: META_VERIFY_TOKEN
        sync: false
      - key: META_PAGE_TOKEN
        sync: false
      - key: PAGE_ID
        value: 1241009282437968
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_ID
        sync: false
